name: PR Unit Tests

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    types: [opened, reopened, synchronize]

permissions:
  contents: read
  checks: write
  pull-requests: write
  issues: write

jobs:
  pr_checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/gradle-wrapper.properties', '**/*.gradle*', '**/gradle.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Run unit tests
        run: ./gradlew --no-daemon jvmTest

      - name: Verify test reports exist
        run: |
          set -e
          count=$(find . -type f -path '*build/test-results/*/TEST-*.xml' 2>/dev/null | wc -l || true)
          echo "Discovered $count test report files."
          if [ "$count" -eq 0 ]; then
            echo "Check locally that all works okay, you can use this command to check ./gradlew jvmTest"
            exit 1
          fi

      # --- Upload artifacts for the publish_test_results.yml workflow ---
      - name: Upload Event File
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Event File
          path: ${{ github.event_path }}

      - name: Upload Test Results (JUnit XML)
        if: always()  # we want them even on failure
        uses: actions/upload-artifact@v4
        with:
          name: Test Results
          path: |
            **/build/test-results/**/TEST-*.xml
          if-no-files-found: warn
          retention-days: 7
